---
- name: Include OS-specific tasks
  include_tasks: "{{ tasks_item }}"
  with_first_found:
    - "setup-{{ ansible_distribution | lower }}.yml"
    - "setup-{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: tasks_item
