---
- name: Get ownCloud client apt key
  apt_key:
    url: '{{ owncloud_apt_repo_key_url }}'
    id: '{{ owncloud_apt_repo_key_id }}'
    state: present

- name: Add ownCloud client repository
  apt_repository:
    repo: '{{ owncloud_apt_repo_source }}'
    state: present

- name: install ownCloud client
  package:
    name: owncloud-client
    state: present
