---
- name: Remove 127.0.1.1 from hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    state: absent

- name: Point localhost to 127.0.0.1
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost localhost.localdomain'
    state: present

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_hostname }}.*' 
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_hostname }}.{{ domainname }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups.all }}"
