---
owncloud_distribution_name: '{{ ansible_distribution }}'
owncloud_distribution_version: '{{ ((ansible_distribution_major_version + ".0") if ansible_distribution in [ "Debian" ] else ansible_distribution_version) }}'
owncloud_distribution: '{{ owncloud_distribution_name + "_" + owncloud_distribution_version }}'

owncloud_apt_repo_base: 'http://download.owncloud.org/download/repositories/stable'
owncloud_apt_repo_key_id: 'DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B'
owncloud_apt_repo_key_url: '{{ owncloud_apt_repo_base + "/" + owncloud_distribution + "/Release.key" }}'
owncloud_apt_repo_source: '{{ "deb " + owncloud_apt_repo_base + "/" + owncloud_distribution + "/ /" }}'
