---
# R-Studio (Ubuntu 18.04 LTS Bionic)
nectar_image_name: "{{ application_name }} ({{ ansible_distribution }} {{ ansible_distribution_version }}{% if 'LTS' in ansible_lsb['description'] %} LTS{% endif %} {{ ansible_distribution_release|capitalize }})"
