---
# Save these vars for setting as image properties
facts:
  - rstudio_version

locale: en_AU.UTF-8

shared_r_modules_path: /mnt

rstudio_version: 1.2.1335
rstudio_server_version: "{{ rstudio_version }}"

r_cran_mirror: https://cran.ms.unimelb.edu.au
r_install_dev: true

r_install:
  - libhdf4-0-alt
  - hdf4-tools
  - libnetcdf-dev
  - netcdf-bin
  - proj-bin
  - libproj-dev
  - libgdal-dev
  - gdal-bin
  - libudunits2-dev
  - libmagick++-dev    # required by animation package
  - libprotobuf-dev    # required by crawl package
  - protobuf-compiler  # required by crawl package
  - libjq-dev          # required by crawl package
  - libv8-dev          # required by crawl package
  - libssl-dev         # required by devtools,httr package

r_packages:
  - name: abind
  - name: ade4
  - name: adehabitatHR
  - name: adehabitatLT
  - name: adehabitatMA
  - name: akima
  - name: animation
  - name: bit
  - name: bitops
  - name: brew
  - name: caTools
  - name: changepoint
  - name: CircStats
  - name: coda
  - name: colorspace
  - name: crawl
  - name: deldir
  - name: devtools
  - name: dichromat
  - name: digest
  - name: dismo
  - name: diveMove
  - name: evaluate
  - name: ff
  - name: FNN
  - name: foreach
  - name: formatR
  - name: gdalUtils
  - name: GeoLight
  - name: geometry
  - name: geosphere
  - name: ggplot2
  - name: gstat
  - name: gtable
  - name: highr
  - name: htmltools
  - name: httpuv
  - name: httr
  - name: intervals
  - name: iterators
  - name: jsonlite
  - name: knitr
  - name: labeling
  - name: magic
  - name: mapdata
  - name: maps
  - name: maptools
  - name: markdown
  - name: memoise
  - name: mime
  - name: misc3d
  - name: munsell
  - name: mvtnorm
  - name: ncdf4
  - name: plyr
  - name: polyclip
  - name: proto
  - name: quantreg
  - name: R6
  - name: raster
  - name: RColorBrewer
  - name: Rcpp
  - name: RCurl
  - name: reshape2
  - name: rgdal
  - name: rgeos
  - name: RJSONIO
  - name: rmarkdown
  - name: R.methodsS3
  - name: RNetCDF
  - name: R.oo
  - name: roxygen2
  - name: rstudioapi
  - name: R.utils
  - name: scales
  - name: shiny
  - name: sp
  - name: spacetime
  - name: SparseM
  - name: stringr
  - name: tensor
  - name: testthat
  - name: trip
  - name: whisker
  - name: XML
  - name: xtable
  - name: xts
  - name: yaml
  - name: zoo

#  - name: ncdf # Error: package 'ncdf' is not available (for R version 3.3.2)
#  - name: rgl  # needs X11

nginx_package_name: nginx-extras
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80 default_server"
    server_name: "_"
    root: "/var/www/html"
    extra_parameters: |
      location /rstudio/ {
        rewrite ^/rstudio/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:8787;
        proxy_redirect http://127.0.0.1:8787/ $scheme://$host/rstudio/;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
      }
      location /shiny/ {
        rewrite ^/shiny/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:3838;
        proxy_redirect http://127.0.0.1:3838/ $scheme://$host/shiny/;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
      }
      location /guacamole/ {
        proxy_pass http://127.0.0.1:8080/guacamole/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        access_log off;
      }

# vim: syntax=yaml
