# vars file for r
---
r_repository: 
  - type: deb
    url: "{{ r_cran_mirror }}/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/"

r_dependencies:
  - r-base
  - r-base-core
  - "{{ 'r-base-dev' if r_install_dev else '' }}"
