---
# https://github.com/voegelas/guacamole-auth-pam
- name: Download PAM Auth
  copy:
    src: files/auth-pam/guacamole-auth-pam-1.2.0.jar
    dest: "{{ guacamole_home }}/extensions"
  notify: restart tomcat

- name: Install Guacamole pam.d config
  copy:
    src: files/auth-pam/pamd-guacamole
    dest: /etc/pam.d/guacamole
  notify: restart tomcat

- name: Install Guacamole PAM auth config
  copy:
    src: files/auth-pam/unix-user-mapping.xml
    dest: "{{ guacamole_home }}/unix-user-mapping.xml"
  notify: restart tomcat

- name: Adding tomcat8 user to shadow group
  user:
    name: tomcat8
    groups: shadow
    append: yes
  notify: restart tomcat
