---
- name: Install XRDP
  package:
    name: '{{ xrdp_packages }}'
    state: present

# XRDP creats this mountpoint in the users home directory which generates
# errors with any file manager, so we simply move it to /tmp out of the way
- name: thinclient_drives fix
  lineinfile:
    path: /etc/xrdp/sesman.ini
    regexp: '^FuseMountName=thinclient_drives'
    line: 'FuseMountName=/tmp/thinclient_drives'


- name: Get the libpulse module directory
  shell: "pkg-config --variable=modlibexecdir libpulse"
  register: libpulse_module_dir

# To build, follow the instructions from
#  https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README
- name: Install XRDP PulseAudio modules
  copy:
    src: "xrdp-pulseaudio/{{ ansible_distribution_release }}/{{ item }}"
    dest: "{{ libpulse_module_dir.stdout }}/{{ item }}"
  with_items:
    - module-xrdp-sink.so
    - module-xrdp-source.so

- name: Start XRDP
  service:
    name: xrdp
    enabled: yes
    state: started
