---
- name: Install XRDP
  package:
    name: '{{ xrdp_packages }}'
    state: present

# XRDP creats this mountpoint in the users home directory which generates
# errors with any file manager, so we simply move it to /tmp out of the way
- name: thinclient_drives fix
  lineinfile:
    path: /etc/xrdp/sesman.ini
    regexp: '^FuseMountName=thinclient_drives'
    line: 'FuseMountName=/tmp/thinclient_drives'

- name: Start XRDP
  service:
    name: xrdp
    enabled: yes
    state: started
