---
- name: write nginx index file
  copy: src=files/index.html dest=/var/www/html/index.html

- name: install extra packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ extra_packages }}"

- name: remove fd0 mount
  mount:
    name: /media/floppy0
    src: /dev/fd0
    state: absent

- name: Adding user www-data to group shadow for nginx pam
  user:
    name: www-data
    groups: shadow
    append: yes
