---
- hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - default_user
    - setup
    - xfce4-desktop
    - x2go-server
    - guacamole
    - tigervncserver
    - r
    - rstudio
    - rstudio-server
    - shiny-server
    - nginx
    - certbot
    - config
    - facts
    - cleanup
