# tasks file for r
---
- name: install | dependencies
  apt:
    name: "{{ r_dependencies }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"

- name: install | additional
  apt:
    name: "{{ r_install }}"
    state: latest
