# tasks file for r
---
- name: repository | add public key
  apt_key:
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    keyserver: keyserver.ubuntu.com
    state: present

- name: repository | add cran-r
  apt_repository:
    repo: "deb {{ r_repository }}"
    state: present
    update_cache: true
