---
- name: Add Certbot PPA
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install Certbot and Certbot NGINX plugin
  apt:
    name:
      - certbot
      - python-certbot-nginx 
    state: present
