---
tomcat_package: tomcat8

guacamole_packages:
  - autoconf
  - build-essential
  - dpkg-dev
  - ghostscript
  - libavcodec-dev
  - libavutil-dev
  - libcairo2-dev
  - libfreerdp-dev
  - libjpeg-dev
  - libjpeg-turbo8-dev
  - libossp-uuid-dev
  - libpango1.0-dev
  - libpng-dev
  - libpulse-dev
  - libssh2-1-dev
  - libssl-dev
  - libswscale-dev
  - libtelnet-dev
  - libvncserver-dev
  - libvorbis-dev
  - libwebp-dev
  - wget
  - xrdp
  - "{{ tomcat_package }}"
